# Generated by Django 6.1 on 2026-08-15 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(default='')),
                ('birth_year', models.IntegerField(default=1950)),
                ('country', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'bookstore_author',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'bookstore_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128)),
                ('joined_on', models.DateField()),
                ('name', models.CharField(max_length=128)),
                ('notes', models.TextField(default='')),
            ],
            options={
                'db_table': 'bookstore_customer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('description', models.TextField(default='')),
                ('founded_year', models.IntegerField(default=1900)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'bookstore_publisher',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'bookstore_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=32)),
                ('page_count', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('published_on', models.DateField()),
                ('summary', models.TextField(default='')),
                ('title', models.CharField(max_length=256)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookstore.author')),
                ('categories', models.ManyToManyField(related_name='books', to='bookstore.category')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookstore.publisher')),
                ('tags', models.ManyToManyField(related_name='books', to='bookstore.tag')),
            ],
            options={
                'db_table': 'bookstore_book',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillment_notes', models.TextField(default='')),
                ('placed_on', models.DateField()),
                ('reference', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bookstore.customer')),
            ],
            options={
                'db_table': 'bookstore_order',
                'ordering': ['-placed_on'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='bookstore.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookstore.order')),
            ],
            options={
                'db_table': 'bookstore_order_item',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='author',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='bookstore.publisher'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='')),
                ('created_on', models.DateField()),
                ('rating', models.IntegerField(default=5)),
                ('reviewer_name', models.CharField(max_length=128)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookstore.book')),
            ],
            options={
                'db_table': 'bookstore_review',
                'ordering': ['-created_on'],
            },
        ),
    ]
